---
title: "EDS 221 day 3 practice"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
pinyon_pine <- 14
lodgepole_pine <- 46

# some logical expressions ----
pinyon_pine == 10
pinyon_pine < lodgepole_pine

pinyon_pine != 25

```

# Conditionals
```{r}
# if statement ----
burrito <- 2.4

if (burrito > 2) {
  print("I love burritos!")
}
```

```{r}
# if-else statement ----
pika <- 89.1

if (pika > 60) {
  print("mega pika")
} else 
  print("normal pika")
```

```{r}
# if-else if-else statement ----
marmot <- 2.8

if (marmot < 0.5) {
  print("a small marmot")
} else if (marmot >= 0.5 & marmot < 3) {
  print("a medium marmot!")
} else
  print("a large marmot!")
```

```{r}
# using string detect ----
library(stringr)

my_ships <- c("Millenium Falcon", "X-wing", "Tie-Fighter", "Death Star")
str_detect(my_ships, pattern = "r")
```

```{r}
# conditional using string detect ----
phrase <- "I hate burritos"

if (str_detect(phrase, "love")) {
  print("burrito fan")
}
```

```{r}
# switch statement ----
species <- "mouse"

switch(species,
       "cat" = print("meow"),
       "dog" = print("woof"),
       "mouse" = print("squeak"))
```

```{r}
if (species == "cat") {
  print("meow")
} else if (species == "dog") {
  print("woof")
} else if (species == "mouse"){
  print("squeak")
}
```

# For loops
```{r}
# for loop using phrase ----
dog_names <- c("Teddy", "Khora", "Banjo", "Waffle")

for (pupster in dog_names) {
  print(paste0("My dog's name is ", pupster, "!"))
}

# for loop using data frame ----
data <- data.frame(x = letters[1:4])
for (i in 1:4) {
  print(data[i,])
}
```

```{r}
# for loop using numbers ----
mass <- seq(from = 0, to = 3, by = 0.5)

for (i in mass) {
  new_value <- i + 2
  print(new_value)
}
```

```{r}
# different way of doing the same thing as above. this might be helpful for sequencing through data frames
mass <- seq(from = 0, to = 3, by = 0.5)

for (i in seq_along(mass)) {
  new_value <- mass[i] + 2
  print(new_value)
}
```

```{r}
tree_height <- c(1, 2, 6, 10)

for (i in seq_along(tree_height)) {
  new_value <- tree_height[i] + tree_height[i+1]
  print(new_value)
}
```

# For loops with conditionals
```{r}
animal <- c("cat", "dog", "dog", "zebra", "dog")

for (i in seq_along(animal)) {
  if (animal[i] == "dog") {
    print("I love dogs")
  } else {
    print("this is not a dog")
  }
}

# this is the same thing, but not as helpful for huge data sets
for (i in animal) {
  if (i == "dog") {
    print("i love dogs")
  } else {
    print("no")
  }
}
```

```{r}
species <- c("dog", "elephant", "goat", "dog", "dog", "elephant")

age_human <- c(3, 8, 4, 6, 12, 18)

for (i in seq_along(species)) {
  if (species[i] == "dog") {
  animal_age <- age_human[i] * 7
} else if (species[i] == "elephant") {
  animal_age <- age_human[i] * 0.88
} else if (species[i] == "goat") {
  animal_age <- age_human[i] * 4.7
}
  print(animal_age)
}

```

# Storing for loop output
```{r}
rm(list = ls())
species <- c("dog", "elephant", "goat", "dog", "dog", "elephant")

# create an empty vector for animal ages
animal_ages <- vector(mode = "numeric", length = length(species))

age_human <- c(3, 8, 4, 6, 12, 18)

for (i in seq_along(species)) {
  if (species[i] == "dog") {
  animal_age <- age_human[i] * 7
} else if (species[i] == "elephant") {
  animal_age <- age_human[i] * 0.88
} else if (species[i] == "goat") {
  animal_age <- age_human[i] * 4.7
}
  animal_ages[i] <- animal_age
}
```

```{r}
tigers <- c(29, 34, 82)
lions <- c(2, 18, 6)

big_cats <- vector(mode = "numeric", length = length(tigers))

for (i in seq_along(tigers)) {
  total_cats <- tigers[i] + lions[i]
  big_cats[i] <- total_cats
}
```

